### ISSUE TITLE
Where is API documentation?

### ISSUE THREAD

**Issue by ceremcem** [kucukkanat/LocalDB#4]
Where is the API documentation? Simple `.insert`, `query` and `remove` is on the README.md but we need full API.

**Comment by kucukkanat** [comment]
Probably the only thing missing is `update` . If you inserted object has `id` then it is updated.

**Comment by kucukkanat** [comment]
From now on there are (CRUD) `.create` `.read` `.update` `.delete` which are aliases to `.insert` , `.query` and `.remove` . Check the new readme
